1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np

2. Create a null vector of size 10 (★☆☆)

In [4]:
a = np.array([0,0,0,0,0,0,0,0,0,0])
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:

# in this case this is not an array
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
a.shape

(10,)

3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.array([0,0,0,0,1,0,0,0,0,0])
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [7]:
x= np.zeros(10)

x[4]=1

print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
np.random.randint(0,8, (3,3))


array([[2, 7, 3],
       [1, 5, 4],
       [4, 2, 4]])

6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [28]:
a = np.nonzero([1,2,0,0,4,0])
print(a)


(array([0, 1, 4], dtype=int64),)


In [13]:
a = [1,2,0,0,4,0]
a_zero = np.nonzero(a)
a

[1, 2, 0, 0, 4, 0]

In [10]:
help(np.nonzero)

Help on function nonzero in module numpy:

nonzero(a)
    Return the indices of the elements that are non-zero.
    
    Returns a tuple of arrays, one for each dimension of `a`,
    containing the indices of the non-zero elements in that
    dimension. The values in `a` are always tested and returned in
    row-major, C-style order.
    
    To group the indices by element, rather than dimension, use `argwhere`,
    which returns a row for each non-zero element.
    
    .. note::
    
       When called on a zero-d array or scalar, ``nonzero(a)`` is treated
       as ``nonzero(atleast_1d(a))``.
    
       .. deprecated:: 1.17.0
    
          Use `atleast_1d` explicitly if this behavior is deliberate.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    tuple_of_arrays : tuple
        Indices of elements that are non-zero.
    
    See Also
    --------
    flatnonzero :
        Return indices that are non-zero in the flattened 

7. Create a 3x3 identity matrix (★☆☆)

In [17]:
a = np.full((3,3), 33)
a

array([[33, 33, 33],
       [33, 33, 33],
       [33, 33, 33]])

8. Create a 3x3x3 array with random values (★☆☆)  to check

In [20]:
a = np.random.random((3,3,3))
a

array([[[0.91395063, 0.4097082 , 0.62073177],
        [0.80103817, 0.22210082, 0.0705483 ],
        [0.99898151, 0.20289831, 0.24926979]],

       [[0.60969799, 0.3125975 , 0.78585591],
        [0.83518221, 0.59786045, 0.57009618],
        [0.83436872, 0.9189124 , 0.90993296]],

       [[0.84206719, 0.99153535, 0.74781164],
        [0.89201915, 0.80634392, 0.12750434],
        [0.26890808, 0.64876625, 0.37415427]]])

9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [27]:
a = np.random.random((10,10))
print(a)


# Mean of all the elements in the first two groups of array b
print(np.max(a[::]))
print(np.min(a[::]))

[[0.32495129 0.80158131 0.19621205 0.42485305 0.41617833 0.50905664
  0.9233053  0.39412492 0.41896842 0.05116474]
 [0.29591997 0.65369814 0.2466819  0.71646084 0.03360429 0.2611815
  0.24391824 0.09502001 0.17741352 0.49622055]
 [0.27114156 0.6246546  0.62172533 0.02027761 0.56418961 0.82415655
  0.02277182 0.90836815 0.26957849 0.07881704]
 [0.0539336  0.08938554 0.36871665 0.91861892 0.16197522 0.79881799
  0.22555982 0.50254773 0.13080571 0.64525164]
 [0.42298352 0.42369865 0.71672599 0.29112971 0.88750682 0.35409686
  0.03953006 0.70997401 0.64046081 0.18181604]
 [0.64494117 0.85455058 0.65464307 0.46242971 0.57595902 0.26434005
  0.31781445 0.72412658 0.35901147 0.15501336]
 [0.82720406 0.15282886 0.49114361 0.52665033 0.76765576 0.46598203
  0.23606047 0.16350835 0.98706193 0.05007841]
 [0.41403204 0.27808531 0.83988102 0.40114683 0.78062161 0.96305828
  0.92171269 0.54951759 0.85530881 0.84092336]
 [0.41874167 0.90165843 0.04267883 0.39148328 0.31196587 0.43909752
  0.55889789 

10. Create a random vector of size 30 and find the mean value (★☆☆)

In [26]:
a = np.arange(0,30)
print(a)

print(np.mean(a[::]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
14.5


11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [30]:
a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [32]:
a = np.diag([1, 2, 3, 4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [36]:
a = np.diag(np.arange(5))
a

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [38]:
a = np.diag(np.arange(4),k=-1)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0]])

12. Normalize a 5x5 random matrix (★☆☆)

In [52]:
a = np.random.random((5,5))

print(a)


amax, amin = a.max(), a.min()
a = (a - amin)/(amax - amin)

print("After normalization:")
print(a)

"""The goal of normalization is to change the values of numeric 
columns in the dataset to a common scale, without distorting 
differences in the ranges of values. For machine learning, 
every dataset does not require normalization. It is required only 
when features have different ranges."""

# normalize the data attributes
#normalized = preprocessing.normalize(a)
#print("Normalized Data = ", normalized)

[[0.72466127 0.39379005 0.91492674 0.18016358 0.07454953]
 [0.67266777 0.89307526 0.59823968 0.91285315 0.65885232]
 [0.54209621 0.2475353  0.84855115 0.88016012 0.59109082]
 [0.05772889 0.14105456 0.33400192 0.07039119 0.60773529]
 [0.16714919 0.40194189 0.71245609 0.09405803 0.47934184]]
After normalization:
[[0.77803787 0.39204621 1.         0.14283132 0.01962282]
 [0.71738267 0.97450825 0.63055547 0.99758097 0.70126568]
 [0.56505895 0.22142661 0.92256679 0.95944155 0.62221567]
 [0.         0.09720705 0.32229786 0.01477173 0.64163298]
 [0.12764883 0.40155608 0.7637994  0.04238128 0.49185022]]


'The goal of normalization is to change the values of numeric \ncolumns in the dataset to a common scale, without distorting \ndifferences in the ranges of values. For machine learning, \nevery dataset does not require normalization. It is required only \nwhen features have different ranges.'

13. How to find common values between two arrays? (★☆☆)

In [17]:
#array01 = np.random.random((5,5))
#array02 = np.random.random((5,5))

a= np.random.randint(0,10,(5,5))
b= np.random.randint(0,10,(5,5))

#print(array01)
#print(array02)

print(a)
print(b)
# Common values between two arrays
print(np.intersect1d(a,b))

[[0 3 3 2 0]
 [9 4 9 9 7]
 [6 1 2 0 1]
 [5 4 1 8 0]
 [3 9 4 0 7]]
[[0 3 5 5 8]
 [5 1 6 8 9]
 [3 4 5 3 9]
 [9 9 8 0 4]
 [7 6 2 3 8]]
[0 1 2 3 4 5 6 7 8 9]


14. Create a random vector of size 10 and sort it (★★☆)

In [56]:
a = np.random.random(10)
print("Original array:")
print(a)
a.sort()
print("Sorted array:")
print(a)

Original array:
[0.47204677 0.84173744 0.57055183 0.74029167 0.56023054 0.8937102
 0.22587    0.16801761 0.98593939 0.97944878]
Sorted array:
[0.16801761 0.22587    0.47204677 0.56023054 0.57055183 0.74029167
 0.84173744 0.8937102  0.97944878 0.98593939]


In [18]:
a= np.random.randint(0,10,(5))
print("Original array:")
print(a)
a.sort()
print("Sorted array:")
print(a)

Original array:
[3 0 8 7 9]
Sorted array:
[0 3 7 8 9]


15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [21]:
a= np.random.randint(0,10,(10))

#a = np.random.random(10)
#a = np.array(np.random.random(10))
print(a)

print(np.max(a))

a[np.argmax(a)]=0

#a[(np.max(a))] = 0

print(a)

[9 4 4 3 0 0 0 0 2 0]
9
[0 4 4 3 0 0 0 0 2 0]


In [71]:
a = np.random.random(10)

print(a)

print(np.max(a))

[0.0457777  0.35726311 0.31973212 0.07973465 0.22232044 0.6109917
 0.77119931 0.18835551 0.79601406 0.3830146 ]
0.7960140559934207


16. Subtract the mean of each row of a matrix (★★☆)

In [4]:
import numpy as np
a= np.random.random((5,3))

#print(a)
#print(a.T)

# Mean of each row in matrix a

b= (np.mean(a, axis=1))

print(b)


first = np.array(b)
second = np.array(b,b)

result= np.concatenate([first, second])
print(result)

#c = (b.T)

#print(c)

#print(a-c)

#print(a-b)



[0.38034035 0.5501378  0.35797512 0.59823437 0.54104529]


TypeError: Cannot construct a dtype from an array

In [25]:
import numpy as np
a= np.random.randint(0,10,(5,3))

print(a)


# Mean of each row in matrix a

b= (np.mean(a, axis=1))

print(b)

#a.sum(axis=1, keepdims=True)

c= np.mean(a, keepdims=True, axis=1)
print(c)


d= a-c

print(d)




[[8 9 0]
 [3 4 2]
 [4 9 5]
 [9 7 9]
 [1 2 6]]
[5.66666667 3.         6.         8.33333333 3.        ]
[[5.66666667]
 [3.        ]
 [6.        ]
 [8.33333333]
 [3.        ]]
[[ 2.33333333  3.33333333 -5.66666667]
 [ 0.          1.         -1.        ]
 [-2.          3.         -1.        ]
 [ 0.66666667 -1.33333333  0.66666667]
 [-2.         -1.          3.        ]]


17. How to get the n largest values of an array (★★★)

In [69]:
a= np.random.random((10,10))

#Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition



print(a)

print(np.max(a))

[[0.88246509 0.4301601  0.36244728 0.92636889 0.97366749 0.19405887
  0.87330374 0.32530721 0.26492245 0.39343394]
 [0.26765263 0.15276287 0.08030389 0.66721227 0.17426365 0.16115525
  0.35582893 0.51801196 0.11773102 0.79202016]
 [0.72977684 0.65433728 0.78416355 0.04176255 0.34627183 0.48652065
  0.90707085 0.84911626 0.50241097 0.86092548]
 [0.73308385 0.63706011 0.44843506 0.75267201 0.26788136 0.84045912
  0.32519098 0.78332731 0.63440293 0.37699268]
 [0.1430941  0.10307876 0.55897218 0.60106419 0.35849437 0.68585132
  0.81750785 0.97616138 0.10602643 0.9817763 ]
 [0.10719363 0.29403945 0.74844976 0.97576119 0.08136214 0.93621456
  0.56230195 0.08912578 0.78195372 0.91523507]
 [0.70694519 0.04422669 0.13159025 0.33071541 0.83860676 0.76603485
  0.63812702 0.49605287 0.87689071 0.14243439]
 [0.32348978 0.99151652 0.8431554  0.17966525 0.57990842 0.05360447
  0.08839493 0.26320002 0.65731476 0.7662914 ]
 [0.30690675 0.56160371 0.51897388 0.84142889 0.56499921 0.70016878
  0.7673506 

In [27]:
# 17
a = np.random.randint(1,1000,(1,1000))
b = np.sort(a)
#print(sortedLargeArray)
print(b[0,-5])
print(b[0,-5:])

995
[995 997 997 999 999]


18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)

In [83]:
#a= np.random.randint((5,3))
a= np.random.randint(0,10,(5,3))

print(a)

[[0 3 6]
 [0 9 4]
 [5 0 1]
 [6 2 3]
 [8 4 8]]


In [84]:
a= np.random.randint(0,10,(5,3))
b = np.where(a<4,a**2,a)
    
print(b)
    

[[0 9 6]
 [0 9 4]
 [5 0 1]
 [6 4 9]
 [8 4 8]]


In [79]:
b = np.where(a>4,0,a)
b

array([[0.58294484, 0.13736403, 0.17662829],
       [0.74956418, 0.10605518, 0.43919319],
       [0.69343715, 0.45581823, 0.5560236 ],
       [0.52862437, 0.31409992, 0.48253794],
       [0.88661368, 0.21880715, 0.15750711]])